### PR TITLE
Abidemi edits

### PR DESCRIPTION
**Pull request by abidemiraji**

### CODE REVIEW

**Comment by jcostasilva** [comment]
Hi Abidemi, great, thanks! Just a note. If I understood correctly, the code now returns SUCCESS even in the case where the target doesn't exist. I'm seeing it right? In that case, what do you think about adding an extra validation to return FAIL: wrong target (or something like that).

**Comment by abidemiraji** [comment]
I could add a validation to pay only internal customers however that would be too restrictive. I thought about that before the commit. Let me know what your thoughts are on this. we could add it in the next sprint

**Comment by mjs09** [comment]
> I could add a validation to pay only internal customers however that would be too restrictive. I thought about that before the commit. Let me know what your thoughts are on this. we could add it in the next sprint

At this stage, I think that the software is not aware of any external customers (that is, accounts at other banks). I'm not sure how we can validate that. For example, if a NewBank customer sends a payment to a customer of OtherBank, there will be no acknowledgement from OtherBank which we can then use to return a SUCCESS or FAIL message.

Perhaps for this part we can assume that we are paying NewBank customers only, then, later we can look at how we pay customers at other banks.

Mitesh

**Comment by jcostasilva** [comment]
@abidemiraji Thanks! Maybe later we can settle upon internal customer vs external and get back to this topic. I'll merge your commit now.

**Pull request merged**
